apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensu-go-deployment.fullname" . }}
  labels:
{{ include "sensu-go-deployment.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.serviceWebsocket.port }}
      targetPort: {{ .Values.serviceWebsocket.port }}
      protocol: TCP
      name: {{ .Values.serviceWebsocket.name }}
    - port: {{ .Values.serviceApi.port }}
      targetPort: {{ .Values.serviceApi.port }}
      protocol: TCP
      name: {{ .Values.serviceApi.name }}
    - port: {{ .Values.serviceDashboard.port }}
      targetPort: {{ .Values.serviceDashboard.port }}
      protocol: TCP
      name: {{ .Values.serviceDashboard.name }}
  selector:
    app.kubernetes.io/name: {{ include "sensu-go-deployment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
